apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rest-villains-pipeline
spec:
  tasks:
    - name: git-clone-1-7-0
      params:
        - name: url
          value: 'https://github.com/pittar-sandbox/quarkus-super-heroes.git'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:8949bb90e05704aef387e5b8d7143f2dc807c8c693c59193a9bb54d8c0e43b21
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone-1-7-0
      workspaces:
        - name: output
          workspace: rest-villains-workspace
    - name: maven-1-7-0
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - package
            - '-DskipTests'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: rest-villains
      runAfter:
        - git-clone-1-7-0
      taskRef:
        kind: ClusterTask
        name: maven-1-7-0
      workspaces:
        - name: source
          workspace: rest-villains-workspace
        - name: maven-settings
          workspace: rest-villains-workspace
    - name: buildah-1-7-0
      params:
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/superhero-battle-cicd/rest-villains:latest
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Containerfile
        - name: CONTEXT
          value: rest-villains
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - maven-1-7-0
      taskRef:
        kind: ClusterTask
        name: buildah-1-7-0
      workspaces:
        - name: source
          workspace: rest-villains-workspace
  workspaces:
    - name: rest-villains-workspace
